#!/bin/sh
set -e

# SET DOCKER_BIN based on if podman or docker exists
if command -v podman >/dev/null 2>&1; then
    DOCKER_BIN=podman
else
    DOCKER_BIN=docker
fi

# Parse argument name with error if not provided
if [ -z "$1" ]; then
    echo "Usage: $0 <release_name>"
    exit 1
fi
RELEASE_NAME=$1
# RELEASE_NAME has form like v0.1.0
VERSION=$(echo "$RELEASE_NAME" | sed 's/^v//')
GHCR_OWNER=$(echo "${GITHUB_REPOSITORY_OWNER:-isawan}" | tr '[:upper:]' '[:lower:]')
IMAGE="ghcr.io/${GHCR_OWNER}/terrashine:${VERSION}"

$DOCKER_BIN manifest create "$IMAGE"

SQLX_OFFLINE=1 cross build --target x86_64-unknown-linux-musl --release --verbose
tar -czf terrashine-x86_64-unknown-linux-musl.tar.gz  -C target/x86_64-unknown-linux-musl/release/  terrashine
$DOCKER_BIN build --manifest "$IMAGE" --platform=linux/amd64 --build-arg HOST_BIN_PATH=target/x86_64-unknown-linux-musl/release/terrashine -f Dockerfile.release

cross clean

SQLX_OFFLINE=1 cross build --target aarch64-unknown-linux-musl --release --verbose
tar -czf terrashine-aarch64-unknown-linux-musl.tar.gz -C target/aarch64-unknown-linux-musl/release/ terrashine
$DOCKER_BIN build --manifest "$IMAGE" --platform=linux/arm64 --build-arg HOST_BIN_PATH=target/aarch64-unknown-linux-musl/release/terrashine -f Dockerfile.release
$DOCKER_BIN manifest push --all "$IMAGE" "$IMAGE"